/*
 * SpoutBreeze open source platform - https://www.spoutbreeze.org/
 *
 * Copyright (c) 2021-2026 RIADVICE SUARL.
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with SpoutBreeze. If not, see <https://www.gnu.org/licenses/>.
 */
package org.spoutbreeze.commons;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.spoutbreeze.commons.data.agent.AgentJdbcRepository;
import org.spoutbreeze.commons.data.broadcast.BroadcastJdbcRepository;
import org.spoutbreeze.commons.data.endpoint.EndpointJdbcRepository;
import org.spoutbreeze.commons.data.server.ServerJdbcRepository;
import org.spoutbreeze.commons.db.JdbcRepository;
import org.spoutbreeze.commons.entities.Agent;
import org.spoutbreeze.commons.entities.Broadcast;
import org.spoutbreeze.commons.entities.Endpoint;
import org.spoutbreeze.commons.entities.Server;
import org.spoutbreeze.commons.enums.AgentStatus;
import org.spoutbreeze.commons.enums.BroadcastStatus;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZonedDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class JdbcRepositoriesTest {
    private static DataSource dataSource;

    private AgentJdbcRepository agents;
    private BroadcastJdbcRepository broadcasts;
    private EndpointJdbcRepository endpoints;
    private ServerJdbcRepository servers;

    @BeforeAll
    static void startDatabase() {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:spoutbreeze;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource = h2;
    }

    @BeforeEach
    void resetSchema() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS agents, broadcasts, streaming_endpoints, servers");
            statement.execute("CREATE TABLE agents (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), status VARCHAR(64), created_on TIMESTAMP, updated_on TIMESTAMP)");
            statement.execute("CREATE TABLE broadcasts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id BIGINT, endpoint_id BIGINT, session_id VARCHAR(255), meeting_id VARCHAR(128), agent_id BIGINT, status VARCHAR(64), created_on TIMESTAMP, updated_on TIMESTAMP)");
            statement.execute("CREATE TABLE streaming_endpoints (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), url VARCHAR(1024), created_on TIMESTAMP, updated_on TIMESTAMP)");
            statement.execute("CREATE TABLE servers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fqdn VARCHAR(255), ip_address VARCHAR(64), shared_secret VARCHAR(255), created_on TIMESTAMP, updated_on TIMESTAMP)");
        }
        agents = new AgentJdbcRepository(dataSource);
        broadcasts = new BroadcastJdbcRepository(dataSource);
        endpoints = new EndpointJdbcRepository(dataSource);
        servers = new ServerJdbcRepository(dataSource);
    }

    private Agent insertAgent(String name) {
        Agent agent = new Agent();
        agent.name = name;
        agent.status = AgentStatus.ENABLED;
        agent.createdOn = ZonedDateTime.now();
        assertThat(agents.insert(agent)).isEqualTo(1);
        return agents.findById(agents.lastInsertedId().lastId.longValue()).orElseThrow();
    }

    @Test
    void agentLifecycle() {
        Agent saved = insertAgent("agent-one");

        assertThat(saved.id).isNotNull();
        assertThat(saved.name).isEqualTo("agent-one");
        assertThat(saved.status).isEqualTo(AgentStatus.ENABLED);

        assertThat(agents.findByName("agent-one").orElseThrow().id).isEqualTo(saved.id);
        assertThat(agents.findByName("missing")).isEmpty();
        assertThat(agents.findById(saved.id).orElseThrow().name).isEqualTo("agent-one");
        assertThat(agents.findById(999L)).isEmpty();
        assertThat(agents.findAllByStatus(AgentStatus.ENABLED)).hasSize(1);
        assertThat(agents.findAllByStatus(AgentStatus.DISABLED)).isEmpty();
        assertThat(agents.findAll()).hasSize(1);

        insertAgent("agent-two");
        assertThat(agents.lastInsertedId().lastId).isEqualTo(2);
        assertThat(agents.deleteById(saved.id)).isEqualTo(1);
        assertThat(agents.deleteById(saved.id)).isEqualTo(0);
    }

    @Test
    void broadcastLifecycle() {
        Agent agent = insertAgent("agent-one");

        Broadcast broadcast = new Broadcast();
        broadcast.server_id = 1L;
        broadcast.endpoint_id = 2L;
        broadcast.meeting_id = "meeting-1";
        broadcast.createdOn = ZonedDateTime.now();
        assertThat(broadcasts.insert(broadcast)).isEqualTo(1);

        Long id = broadcasts.lastInsertedId().lastId.longValue();
        Broadcast saved = broadcasts.findById(id).orElseThrow();
        assertThat(saved.server_id).isEqualTo(1L);
        assertThat(saved.endpoint_id).isEqualTo(2L);
        assertThat(saved.meeting_id).isEqualTo("meeting-1");
        assertThat(broadcasts.findByMeetingId("meeting-1").orElseThrow().id).isEqualTo(id);
        assertThat(broadcasts.findReadyBroadcast().orElseThrow().id).isEqualTo(id);
        assertThat(broadcasts.updateSessionId(id, "session-1")).isEqualTo(1);
        assertThat(broadcasts.findById(id).orElseThrow().session_id).isEqualTo("session-1");
        assertThat(broadcasts.assignToAgent(saved, agent.id)).isEqualTo(1);
        assertThat(broadcasts.findById(id).orElseThrow().status).isEqualTo(BroadcastStatus.ASSIGNED);
        assertThat(broadcasts.findById(id).orElseThrow().agent_id).isEqualTo(agent.id);

        assertThat(broadcasts.updateStatus(id, BroadcastStatus.LIVE)).isEqualTo(1);
        assertThat(broadcasts.findLiveByMeetingId("meeting-1").orElseThrow().id).isEqualTo(id);
        assertThat(broadcasts.releaseAgent(id)).isEqualTo(1);
        assertThat(broadcasts.findById(id).orElseThrow().agent_id).isNull();

        assertThat(broadcasts.findAll()).hasSize(1);
        assertThat(broadcasts.deleteById(id)).isEqualTo(1);
        assertThat(broadcasts.deleteById(id)).isEqualTo(0);
        assertThat(broadcasts.findById(id)).isEmpty();
    }

    @Test
    void endpointLifecycle() {
        Endpoint endpoint = new Endpoint();
        endpoint.name = "youtube";
        endpoint.url = "rtmp://a.example.com/live";
        endpoint.createdOn = ZonedDateTime.now();
        assertThat(endpoints.insert(endpoint)).isEqualTo(1);

        Long id = endpoints.lastInsertedId().lastId.longValue();
        assertThat(endpoints.findById(id).orElseThrow().name).isEqualTo("youtube");
        assertThat(endpoints.findByName("youtube").orElseThrow().url).startsWith("rtmp://");
        assertThat(endpoints.findByName("missing")).isEmpty();
        assertThat(endpoints.findAll()).hasSize(1);
        assertThat(endpoints.deleteById(id)).isEqualTo(1);
        assertThat(endpoints.findAll()).isEmpty();
    }

    @Test
    void serverLifecycle() {
        Server server = new Server();
        server.fqdn = "bbb.example.com";
        server.ipAddress = "192.0.2.10";
        server.sharedSecret = "secret";
        server.createdOn = ZonedDateTime.now();
        assertThat(servers.insert(server)).isEqualTo(1);

        Long id = servers.lastInsertedId().lastId.longValue();
        assertThat(servers.findById(id).orElseThrow().fqdn).isEqualTo("bbb.example.com");
        assertThat(servers.findByName("bbb.example.com").orElseThrow().sharedSecret).isEqualTo("secret");
        assertThat(servers.findByName("missing")).isEmpty();
        assertThat(servers.findAll()).hasSize(1);
        assertThat(servers.deleteById(id)).isEqualTo(1);
        assertThat(servers.findAll()).isEmpty();
    }

    @Test
    void sqlFailureIsWrapped() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE agents");
            statement.execute("DROP TABLE streaming_endpoints");
        }

        assertThatThrownBy(() -> agents.findAllByStatus(AgentStatus.ENABLED))
                .isInstanceOf(JdbcRepository.DataAccessException.class);

        assertThatThrownBy(() -> endpoints.findAll())
                .isInstanceOf(JdbcRepository.DataAccessException.class);
    }
}
