# SpoutBreeze open source platform - https://www.spoutbreeze.org/
#
# Copyright (c) 2021-2026 RIADVICE SUARL.
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with SpoutBreeze. If not, see <https://www.gnu.org/licenses/>.

micronaut.application.name=spoutbreeze-agent
micronaut.server.port=21030
grid.endpoint=${GRID_ENDPOINT:http://localhost:4444/wd/hub}
spoutbreeze.api.url=${SPB_API_URL:http://localhost:8091}
spoutbreeze.api.key=${SPB_API_KEY:spoutbreeze-dev-api-key}
micronaut.http.services.spoutbreeze-api.url=${spoutbreeze.api.url}
micronaut.http.services.spoutbreeze-api.read-timeout=10s
rabbitmq.uri=${RABBITMQ_URI:amqp://spoutbreeze:spoutbreeze@localhost:5672}
agent.queue=spoutbreeze_agent.${AGENT_NAME:local}
datasources.default.url=${JDBC_URL:jdbc:postgresql://localhost:5432/spoutbreeze}
datasources.default.username=${JDBC_USER:spoutbreeze_u}
datasources.default.password=${JDBC_PASSWORD:spoutbreeze_pass}
datasources.default.driver-class-name=org.postgresql.Driver
endpoints.health.enabled=true
