# SpoutBreeze open source platform - https://www.spoutbreeze.org/
#
# Copyright (c) 2021-2026 RIADVICE SUARL.
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with SpoutBreeze. If not, see <https://www.gnu.org/licenses/>.

server {
  listen 80;
  server_name _;

  root /var/www/spoutbreeze-web/public;
  index index.php;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  location / {
    try_files $uri $uri/ @f3;
  }

  location @f3 {
    rewrite ^ /index.php;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass web-legacy-php:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTP_HOST $http_host;
    fastcgi_read_timeout 60;
  }

  location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff2?|ttf)$ {
    expires 7d;
    access_log off;
    try_files $uri =404;
  }
}
