; SpoutBreeze open source platform - https://www.spoutbreeze.org/
;
; Copyright (c) 2021-2026 RIADVICE SUARL.
;
; This program is free software: you can redistribute it and/or modify it under the
; terms of the GNU Affero General Public License as published by the Free Software
; Foundation, either version 3 of the License, or (at your option) any later version.
;
; SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
; WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
; PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License along
; with SpoutBreeze. If not, see <https://www.gnu.org/licenses/>.

[globals]
; Stack trace verbosity. Assign values 1 to 3 for increasing verbosity levels. Zero (0) suppresses the stack trace.
; This is the default value and it should be the assigned setting on a production server.
DEBUG = 0

; The PHP Package to show in requests
PACKAGE = Sukarix - Just the Right Amount of Sweetness and Efficiency on Top of Fat-Free

;Location of custom logs.
LOGS = ../logs/

; Temporary folder for cache, filesystem locks, compiled F3 templates, etc. Default is the tmp/ folder outside the Web root.
; Adjust accordingly to conform to your site's security policies.
TEMP = ../tmp/

; Directory where file uploads are saved.
UPLOADS = ../uploads/

; Search path for user interface files used by the View and Template classes' render() method. Default value is the Web root.
; Accepts a pipe (|), comma (,), or semi-colon (;) as separator for multiple paths.
UI = templates/;../public/;

; Location of the language dictionaries.
LOCALES = i18n/
ENCODING = UTF-8

; Current active language. Value is used to load the appropriate language translation file in the folder pointed to by LOCALES.
; If set to NULL, language is auto-detected from the HTTP Accept-Language request header.
LANGUAGE = en-GB
FALLBACK = en-GB

; cache configuration
CACHE = folder=tmp/cache/

; Cache seed
SEED = sukarix

; turn javascript and css minification on and off
MINIFY_JS = TRUE
MINIFY_CSS = TRUE

; timezone settings
TZ = UTC

; configuration files to load in the mentioned order
CONFIGS = smtp,notifications,upload,spoutbreeze

; set to development|testing|staging|production|local or whatever you like
application.environment = production

; default locale for new sessions
application.locale = en-GB

; log session queries
; log.session = false

; session parameters
; session.table = users_sessions
session.table = CACHE

; pagination
pagination.limit = 12

; default view to render
template.default = website

; log clean after x days
log.keep = 14

; server host for command line actions
server.host =

; error notification channel "email" or "zulip"
error.channel =


[SECURITY]
csrf.enabled = true
csrf.expiry = 3600

[SECURITY.stateless]
prefixes = /api,/healthz,/readyz
