/*
 * SpoutBreeze open source platform - https://www.spoutbreeze.org/
 *
 * Copyright (c) 2021-2026 RIADVICE SUARL.
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with SpoutBreeze. If not, see <https://www.gnu.org/licenses/>.
 */
plugins {
	id 'io.micronaut.application' version '5.0.2'
	id 'com.gradleup.shadow' version '9.6.1'
	id 'jacoco'
}

group = 'org.spoutbreeze'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

micronaut {
	version = '5.1.3'
	runtime('netty')
	testRuntime('junit5')
	processing {
		incremental(true)
		annotations('org.spoutbreeze.agent.*')
	}
}

dependencies {
	implementation(project(':spoutbreeze-commons'))
	implementation('io.micronaut:micronaut-jackson-databind')
	implementation('io.micronaut:micronaut-management')
	implementation('io.micronaut:micronaut-http-client')
	implementation('io.micronaut.sql:micronaut-jdbc-hikari')
	implementation('io.micronaut.rabbitmq:micronaut-rabbitmq')
	implementation('com.rabbitmq:http-client:5.7.0')
	implementation('org.seleniumhq.selenium:selenium-java:4.49.0')
	runtimeOnly('org.postgresql:postgresql')
	runtimeOnly('org.slf4j:slf4j-simple')

	testImplementation('org.mockito:mockito-core:5.23.0')
	testImplementation('org.assertj:assertj-core:3.27.7')
}

application {
	mainClass.set('org.spoutbreeze.agent.AgentApplication')
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	reports {
		xml.required = true
	}
}
