<div class="page-header">
    <h1 class="page-title">
        Broadcasts
    </h1>

</div>

<div class="row row-deck">
    <div class="col-12">
        <div class="card">
            <div class="table-responsive">
                <table class="table card-table table-vcenter text-nowrap datatable table-listing">
                    <thead>
                    <tr>
                        <th class="w-1p">ID</th>
                        <th>selenoid id</th>
                        <th>server id</th>
                        <th>endpoint id</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>





