<js src="vendors/jquery-3.2.1.min.js"/>
<js src="vendors/bootstrap.bundle.min.js"/>
<!--<js src="vendors/tabler.min.js"/>-->
<js src='plugins/noty/jquery.noty.packaged.js'/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

<js src="core/plugins.js"/>
<js src="core/locale.js"/>
<js src="core/common.js"/>

{{ \Helpers\Assets::instance()->renderGroup('footer') }}

<script>
    jQuery(document).ready(function () {
        {{ \Helpers\Assets::instance()->currentJsLocale() }}
        {{ \Helpers\Assets::instance()->setUserRole() }}
        {{ \Helpers\Assets::instance()->initJsClasses() }}
        {{ \Helpers\Flash::instance()->showMessages() }}
    });
</script>
