<div class="page">
    <div class="page-single">
        <div class="container">
            <div class="row">
                <div class="col col-login mx-auto">
                    <div class="text-center mb-6">
                        <img src="/img/logo.png" class="h-9" alt="SpoutBreeze">
                    </div>
                    <form class="card" action="" method="post">
                        <div class="card-body p-6">
                            <div class="card-title">Login to your account</div>
                            <div class="form-group">
                                <label class="form-label">Email address</label>
                                <input type="email" class="form-control" name="email" value="{{@@data.email}}"
                                       aria-describedby="emailHelp" placeholder="Enter email">
                                <form_error name="email"/>
                            </div>
                            <div class="form-group">
                                <label class="form-label">
                                    Password
                                    <!--<a href="./forgot-password.html" class="float-right small">I forgot password</a>-->
                                </label>
                                <input type="password" class="form-control" name="password" value="{{@@data.password}}"
                                       placeholder="Password">
                                <form_error name="password"/>
                            </div>
                            <div class="form-group">
                                <label class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input"/>
                                    <span class="custom-control-label">Remember me</span>
                                </label>
                            </div>
                            <div class="form-footer">
                                <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                            </div>
                        </div>
                    </form>
                    <!--<div class="text-center text-muted">
                        Don't have account yet? <a href="./register.html">Sign up</a>
                    </div>-->
                </div>
            </div>
        </div>
    </div>
</div>
