#!/bin/bash

#
# SpoutBreeze open source platform - https://www.spoutbreeze.org/
#
# Copyright (c) 2021 Frictionless Solutions Inc., RIADVICE SUARL and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# SpoutBreeze is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with SpoutBreeze; if not, see <http://www.gnu.org/licenses/>.
#
# Author(s):
#       GTR - Ghazi Triki <ghazi.triki@riadvice.tn>
#
# Changelog:
#   2021-03-03 GTR Initial Version

# The real location of the script
SCRIPT=$(readlink -f "$0")

# Current unix username
USER=$(whoami)

# Directory where the script is located
BASEDIR=$(dirname "$SCRIPT")

# Formatted current date
NOW=$(date +"%Y-%m-%d_%H.%M.%S")

# Production SpoutBreeze Command line-tool directory
APP_DIR=$BASEDIR/../

# Command line tool logs directory
CMD_LOG_DIR="$HOME"

# Production application directories
WEB_DIR="/var/www/spoutbreeze-web/"

# Current git branch name transforms '* dev-0.5' to 'dev-0.5'
GIT_BRANCH=$(git --git-dir="$BASEDIR/../.git" branch | sed -n '/\* /s///p')

# Git tag, commits ahead & commit id under format '0.4-160-g3bb256c'
GIT_VERSION=$(git --git-dir="$BASEDIR/../.git" describe --tags --always HEAD)

#
# Display usage
#
usage() {
  echo
  echo "#========================================================================================================"
  echo "#"
  echo "# Configuration Utility for SpoutBreeze - Version $GIT_VERSION on $GIT_BRANCH branch"
  echo "#"
  echo "#    spoutbreeze [options]"
  echo "#"
  echo "# Configuration:"
  echo "#    --version                        Display SpoutBreeze version"
  echo "#    --selfinstall                    Make spoutbreeze runnable from anywhere"
  echo "#"
  echo "# Development:"
  echo "#    --enabletests                    Enable running unit tests"
  echo "#    --test <-c> <name>               Run unit tests with a test name. Use for -c coverage"
  echo "#    --fix                            Fix php code style"
  echo "#    --migrate                        Run database migrations"
  echo "#    --metrics                        Generates code metrics"
  echo "#"
  echo "# Monitoring:"
  echo "#    --check                          Check configuration files and processes for problems"
  echo "#"
  echo "# Administration:"
  echo "#    --install                        Installs SpoutBreeze packages"
  echo "#    --pull                           Pull source code from its repository"
  echo "#    --deploy                         Deploy the application on a production server"
  echo "#    --jobs                           Install the cron jobs"
  echo "#    --restart                        Restart SpoutBreeze"
  echo "#    --stop                           Stop SpoutBreeze"
  echo "#    --start                          Start SpoutBreeze"
  echo "#    --clean                          Restart and clean all log files"
  echo "#    --cleansessions                  Cleans sessions from the database"
  echo "#    --status                         Display running status of components"
  echo "#    --zip                            Zip up log files for reporting an error"
  echo "#"
  echo "#========================================================================================================"
  echo
}

#
# Check file
#
check_file() {
  if [ ! -f "$1" ]; then
    echo "✘ File does not exist: $1"
    # m option means that the file is mandatory and the script cannot continue running
    if [ "$2" == "m" ]; then
      echo "✘ File $1 is mandatory. Script execution is interrupted"
      exit 1
    fi
  fi
}

need_production() {
  if [ "$ENVIRONMENT" != "production" ]; then
    echo "✘ Command can only be run in production environment"
    exit 1
  fi
}

#
# Display installed SpoutBreeze & servers version
#
display_version() {
  echo "■ SpoutBreeze :  $GIT_VERSION"
  echo "■ Nginx       :  $(nginx -v)"
  echo "■ PHP         :  $(php -v | sed -n 1p)"
  echo "■ Redis       :  $(redis-server --version)"
  echo "■ PostgreSQL  :  $(psql -V)"
}

#
# Install spoutbreeze to make runnable from anywhere
#
self_install() {
  if [ -f /usr/local/bin/spoutbreeze ]; then
    echo "✘ spoutbreeze already installed"
  else
    sudo ln -s "$SCRIPT" /usr/local/bin/spoutbreeze
    echo "✔ spoutbreeze successfully installed"
  fi
}

#
# Installs all the server packages
#
install_server() {
  sudo apt-get install -y git curl software-properties-common gnupg gnupg2

  sudo add-apt-repository -y ppa:ondrej/php

  sudo wget https://repo.percona.com/apt/percona-release_latest.generic_all.deb
  sudo dpkg -i percona-release_latest.generic_all.deb
  sudo rm percona-release_latest.generic_all.deb

  sudo apt-get update
  sudo apt-get upgrade -y

  sudo apt-get install -y wget lsb-release curl zip unzip nginx-full bc ntp xmlstarlet bash-completion
  sudo apt-get install -y redis
  sudo apt-get install -y php8.0-curl php8.0-cli php8.0-intl php8.0-redis php8.0-gd php8.0-fpm php8.0-pgsql php8.0-mbstring php8.0-xml php8.0-bcmath php-xdebug

  sudo percona-release setup ppg-13.1
  sudo apt-get install -y percona-postgresql-13 percona-postgresql-13-pgaudit percona-pg-stat-monitor13
  sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
  sudo apt install -y certbot

  sudo service nginx stop
  sudo certbot certonly --standalone --non-interactive --preferred-challenges http --deploy-hook "sudo service nginx start" -d $(hostname) --email devops@riadvice.tn,sdame@207me.com --agree-tos -n
  # generate db password
  # configure password in in files
  # configure nginx site
  # configure php-fpm
}

#
# Clean server status
#
display_status() {
  units="nginx php-fpm postgresql redis"
  echo
  line='————————————————————►'
  for unit in $units; do
    if [ $(pgrep -c "$unit") != 0 ]; then
      printf "%s %s [✔ - UP]\n" $unit "${line:${#unit}}"
    else
      printf "%s %s [✘ - DOWN]\n" $unit "${line:${#unit}}"
    fi
  done
  echo
}

#
# Clean SpoutBreeze cache
#
clean_cache() {
  echo "► Deleting cache"
  find "$BASEDIR/../bin/" ! -name '.gitkeep' -type f -exec rm -rfv {} \;
  find "$BASEDIR/../tmp/" ! -name '.gitkeep' -type f -exec rm -rfv {} \;
  find "$BASEDIR/../tmp/cache/" ! -name '.gitkeep' -type f -exec rm -rfv {} \;
  find "$BASEDIR/../tmp/mail/" -name '*.eml' -type f -exec rm -v {} \;
  find "$BASEDIR/../uploads/tmp/" -type f -exec rm -v {} \;
  find "$BASEDIR/../public/minified/" ! -name '.gitkeep' -type f -exec rm -v {} \;
  echo "✔ Cache deleted"
}

#
# Clean SpoutBreeze cache
#
clean_logs() {
  echo "► Cleaning logs"

  find "$CMD_LOG_DIR/logs/" ! -name '.gitkeep' -type f -exec rm -v {} \;

  echo "✔ Cleaned logs folder"
}

#
# Clean sessions from the database
#
clean_sessions() {
  sudo -u postgres psql -d bbb_lb -c "SELECT setval('users_sessions_id_seq'::regclass, 1);"
  sudo -u postgres psql -d bbb_lb -c "TRUNCATE users_sessions;"
}

#
# Archive logs for debugging
#
zip_logs() {
  echo "► Archiving logs"

  ARCHIVE="$CMD_LOG_DIR/logs/logs-$NOW.tar.gz"
  mkdir -p "$CMD_LOG_DIR/logs/"

  touch /tmp/empty
  tar cfv "$ARCHIVE" /tmp/empty
  tar rfv "$ARCHIVE" "$BASEDIR/../logs/" --exclude='.gitkeep'
  sudo tar rfv "$ARCHIVE" /var/log/nginx/
  echo "✔ Logs archived at $ARCHIVE"
}

#
# Run PHP Code Style Fixer
#
fix_styles() {
  echo "► Running PHP Code Style Fixer"

  cd "$BASEDIR/../"

  sudo phpdismod -s cli xdebug
  ./vendor/bin/php-cs-fixer fix --allow-risky=yes
  sudo phpenmod -s cli xdebug
  echo "✔ PHP Code Style Fixed"
}

#
# Enable unit tests
#
enable_tests() {
  echo "► Enabling unit tests"

  rm -rfv "$BASEDIR/../public/hypertest/"
  mkdir -pv "$BASEDIR/../public/hypertest/coverage/"
  mkdir -pv "$BASEDIR/../public/hypertest/result/"
  cp -Rv "$BASEDIR/../tools/hypertest.php" "$BASEDIR/../public/hypertest/index.php"
  cp -Rv "$BASEDIR/../tests/ui/css" "$BASEDIR/../public/hypertest/"
  cp -Rv "$BASEDIR/../tests/ui/images" "$BASEDIR/../public/hypertest/"
  cp -Rv "$BASEDIR/../tests/ui/css" "$BASEDIR/../public/hypertest/result"
  cp -Rv "$BASEDIR/../tests/ui/images" "$BASEDIR/../public/hypertest/result"
  cp "$BASEDIR/../vendor/bcosca/fatfree-core/code.css" "$BASEDIR/../public/hypertest/css/code.css"
  cp "$BASEDIR/../vendor/bcosca/fatfree-core/code.css" "$BASEDIR/../public/hypertest/result/css/code.css"

  echo "✔ Unit tests enabled"
}

#
# Run unit test in CLI mode
#
run_tests() {
  echo "► Running unit tests"
  COVERAGE=$1
  USE_COVERAGE=""
  TEST_NAME="all"

  if [[ "$1" != "-c" ]]; then
    if [[ "$1" != "" ]]; then
      TEST_NAME=$1
    fi

    if [[ "$2" == "-c" ]]; then
      USE_COVERAGE="=withCoverage"
    fi
  fi

  if [[ "$1" == "-c" ]]; then
    USE_COVERAGE="=withCoverage"
    if [[ "$2" != "" ]]; then
      TEST_NAME=$2
    fi
  fi

  cd $(dirname "$BASEDIR")
  # Revert database base to the initial state then create it again
  "vendor/bin/phinx" rollback -e testing -t 0 -vvv
  "vendor/bin/phinx" migrate -e testing -vvv

  cd "public"

  php index.php "/?hypertest$USE_COVERAGE&test=$TEST_NAME" -o="../public/hypertest/result/index.html"

  SUCCESS=$(cat "hypertest/test.result")
  if [[ "$SUCCESS" == "success" ]]; then
    echo "✔ Test success"
    exit 0
  else
    echo "✘ Test fail"
    exit 1
  fi
}

#
# Install the cron jobs
#
install_cron_job() {
  echo "► Installing cron jobs"
  if [ "$ENVIRONMENT" != "production" ]; then
    sudo crontab -l -u vagrant | cat - "$BASEDIR/../tools/spoutbreeze-tasks" | sudo crontab -u vagrant -
  else
    sudo crontab -l -u www-data | cat - "$BASEDIR/../tools/spoutbreeze-tasks" | sudo crontab -u www-data -
  fi
  sudo /etc/init.d/cron reload
}

#
# Updates composer and reset user home composer ownership
#
update_composer() {
  echo "► Updating composer"
  sudo composer selfupdate
  sudo chown -R "$USER:$USER" "/home/$USER/.composer/"
}

#
# Fetch the source code from its repository
#
update_source_code() {
  need_production
  echo "► Pulling source code in $APP_DIR"
  cd "$APP_DIR"
  git pull
}

# Install composer dependencies
#
install_dependencies() {
  cd $(dirname "$BASEDIR")
  echo "► Updating composer dependencies"
  composer install -o --no-dev
}

#
# Run database migrations
#
run_migrations() {
  echo "► Running database migration"
  cd $(dirname "$BASEDIR")
  vendor/bin/phinx migrate -e "$ENVIRONMENT"
}

#
# Generate code quality metrics
#
generate_metrics() {
  vendor/bin/phpmetrics --report-html="$BASEDIR/../public/metrics" "$BASEDIR/../app/src/"
}

#
# Give folders right permissions
#
chmod_folders() {
  cd "$APP_DIR"
  sudo chmod -R 755 -R "$WEB_DIR/../data/"
  sudo chmod -R 766 -R "$WEB_DIR/../logs/"
  sudo chmod -R 766 -R "$WEB_DIR/../tmp/"
  sudo chmod -R 755 -R "$WEB_DIR/../uploads/"
  sudo chmod -R 755 -R "$WEB_DIR/../public/minified/"
}

#
# Fully deploys all the application
#
deploy_application() {
  need_production
  cd "$APP_DIR"
  sudo chown -R "$USER:$USER" .
  update_source_code
  update_composer
  install_dependencies
  run_migrations
  sudo chown -R "www-data:www-data" .
  chmod_folders
  # install_cron_job
  restart_services
}

#
# Start services
#
start_services() {
  sudo service postgresql start
  sudo service redis start
  sudo service nginx start
  sudo service php8.0-fpm start
}

#
# Stop services
#
stop_services() {
  sudo service postgresql stop
  sudo service redis stop
  sudo service nginx stop
  sudo service php8.0-fpm stop
}

#
# Restart services
#
restart_services() {
  sudo service postgresql restart
  sudo service redis restart
  sudo service nginx restart
  sudo service php8.0-fpm restart
}

run() {

  if [[ $# -eq 0 ]]; then
    usage
    exit 1
  fi

  # Environment
  HOST_TESTER=$(hostname)
  if [[ "$HOST_TESTER" == "spoutbreeze" ]]; then
    ENVIRONMENT="development"
  else
    ENVIRONMENT="production"
  fi

  echo "► Detected environment: \`$ENVIRONMENT\`"

  while [[ $# -gt 0 ]]; do

    if [ "$1" = "--version" -o "$1" = "-version" -o "$1" = "-v" ]; then
      display_version
      shift
      continue
    fi

    if [ "$1" = "--selfinstall" -o "$1" = "-selfinstall" -o "$1" = "-si" ]; then
      self_install
      shift
      continue
    fi

    if [ "$1" = "--enabletests" -o "$1" = "-enabletests" -o "$1" = "-e" ]; then
      enable_tests
      shift
      continue
    fi

    if [ "$1" = "--test" -o "$1" = "-test" -o "$1" = "-t" ]; then
      run_tests "$2" "$3"

      shift
      shift
      continue
    fi

    if [ "$1" = "--check" -o "$1" = "-check" ]; then
      # todo: nginx config, postgresql, config, directories permissions...
      echo "not implemented yet"
      shift
      continue
    fi

    if [ "$1" = "--fix" -o "$1" = "-fix" -o "$1" = "-f" ]; then
      fix_styles
      shift
      continue
    fi

    if [ "$1" = "--migrate" -o "$1" = "-migrate" -o "$1" = "-m" ]; then
      run_migrations
      shift
      continue
    fi

    if [ "$1" = "--metrics" -o "$1" = "-metrcis" -o "$1" = "-me" ]; then
      generate_metrics
      shift
      continue
    fi

    if [ "$1" = "--clean" -o "$1" = "-clean" ]; then
      clean_cache
      clean_logs
      shift
      continue
    fi

    if [ "$1" = "--cleansessions" -o "$1" = "-cleansessions" -o "$1" = "-cs" ]; then
      clean_sessions
      shift
      continue
    fi

    if [ "$1" = "--pull" -o "$1" = "-pull" -o "$1" = "-p" ]; then
      update_source_code
      shift
      continue
    fi

    if [ "$1" = "--install" -o "$1" = "-install" -o "$1" = "-i" ]; then
      install_server
      shift
      continue
    fi

    if [ "$1" = "--deploy" -o "$1" = "-deploy" -o "$1" = "-d" ]; then
      deploy_application
      shift
      continue
    fi

    if [ "$1" = "--jobs" -o "$1" = "-jobs" -o "$1" = "-j" ]; then
      install_cron_job
      shift
      continue
    fi

    if [ "$1" = "--restart" -o "$1" = "-restart" -o "$1" = "-r" ]; then
      restart_services
      shift
      continue
    fi

    if [ "$1" = "--stop" -o "$1" = "-stop" -o "$1" = "-sp" ]; then
      stop_services
      shift
      continue
    fi

    if [ "$1" = "--start" -o "$1" = "-start" -o "$1" = "-sr" ]; then
      start_services
      shift
      continue
    fi

    if [ "$1" = "--status" -o "$1" = "-status" ]; then
      display_status
      shift
      continue
    fi

    if [ "$1" = "--zip" -o "$1" = "-zip" -o "$1" = "-z" ]; then
      zip_logs
      shift
      continue
    fi

    usage
    exit 1

  done
}

run "$@" #2>&1 | tee -a "$BASEDIR/../logs/spoutbreeze-$NOW.log"
